import { cobiTLogo, dashboardIcon1 } from "@/assets";

export const PeriodicBoxData = [
    {
        id: 1,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
    },
    {
        id: 2,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
    },
    {
        id: 3,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 4,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 5,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 6,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 7,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 8,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#27475E",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#BC6B3C",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#BC6B3C",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#FF6D41",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#B89959",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#B89959",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#B89959",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#B89959",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
        reverse: "column-reverse",
    },
    {
        id: 9,
        color: "#BC6B3C",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#BC6B3C",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#1E807F",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
    },
    {
        id: 9,
        color: "#1E807F",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#1E807F",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#1E807F",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4184BB",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4184BB",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4184BB",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
        reverse: "column-reverse",
    },
    {
        id: 9,
        color: "#7A1F48",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#7A1F48",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4A516B",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
        reverse: "column-reverse",
    },
    {
        id: 9,
        color: "#4A516B",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
        reverse: "column-reverse",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4184BB",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4184BB",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#7A1F48",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#7A1F48",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#4A516B",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#7A1F48",
        title: "Managed Assurance",
        tileText: "MEA04",
        topTitle: "Strategy & Governance",
    },
    {
        id: 9,
        color: "#4A516B",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
    {
        id: 9,
        color: "#222AA1",
        title: "Managed Assurance",
        tileText: "MEA04",
    },
];


export const periodicTableArray = [
    {
        mainTable: [
            { mainTitle: "Strategy & Governance", colspan: 1, color: "#27475E" },
            {},
            {},
            {},
            { mainImage: { cobit: cobiTLogo, }, colspan: 1 },
            {},
            {},
            {},
            {},
            { mainTitle: "Security & Risk", colspan: 1, color: "#FF6D41" },
        ],
    },
    {
        mainTable: [
            {
                name: "Managed Assurance",
                code: "MEA04",
                image: dashboardIcon1,
                background: "#27475E",
            },
            {},
            {},
            { mainHeading: "IT Management & Governance Framework.", colspan: 4 },
            { colspan: 2 },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                colspan: null,
                background: "#FF6D41",
            },
        ],
    },
    {
        mainTable: [
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },

            { colspan: 1 },
            {
                mainTitle: "Data & BI",
                colspan: 1,
                textRight: true,
                color: "#BC6B3C",
            },
            {},
            {},
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
        ],
    },
    {
        mainTable: [
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#27475E",
            },
            { mainTitle: "People and resources", border: true, color: "#B89959" },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#BC6B3C",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#BC6B3C",
            },
            { mainTitle: "Security & Risk", border: true, color: "#1E807F" },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#FF6D41",
            },
        ],
    },
    {
        mainTable: [
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#B89959",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#B89959",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#B89959",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#B89959",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#BC6B3C",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#BC6B3C",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#1E807F",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#1E807F",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#1E807F",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#1E807F",
            },
        ],
    },
    {
        mainTable: [
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4184BB",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4184BB",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4184BB",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#7A1F48",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#7A1F48",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4A516B",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4A516B",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
        ],
    },
    {
        mainTable: [
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4184BB",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4184BB",
            },
            {
                mainTitle: "Service Planning & Architecture",
                colspan: 1,
                color: "#4184BB",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#7A1F48",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#7A1F48",
            },
            {
                mainTitle: "People & Resources",
                colspan: 1,
                color: "#4A516B",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4A516B",
            },

            {
                mainTitle: "Infrastructure & Operations",
                colspan: 1,
                textRight: true,
                color: "#222AA1",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },

        ],
    },
    {
        mainTable: [
            {},
            {},
            {},
            {},
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#7A1F48",
            },
            {},
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#4A516B",
            },
            {},
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
        ],
    },
    {
        mainTable: [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {
                name: "IT Governance",
                code: "EDM01",
                image: dashboardIcon1,
                background: "#222AA1",
            },
        ],
    },
];