// export { default as CommonBackIcon } from "./common-back.svg";
// export { default as MultiBackIcon } from "./multi-back.svg";
// export { default as BackVectorIcon } from "./back-vector.svg";
// export { default as AntisocialPersonalityDisorderIcon } from "./antisocialpersonality-disorder.svg";
// export { default as AnxietyDisordersImg1 } from "./anxiety-disorders-img-1.svg";
// export { default as AnxietyDisordersImg2 } from "./anxiety-disorders-img-2.svg";
// export { default as AnxietyDisordersImg3 } from "./anxiety-disorders-img-3.svg";
// export { default as AnxietyDisordersImg4 } from "./anxiety-disorders-img-4.svg";
// export { default as BipolarDisorderIcon } from "./bipolar-disorder.svg";
// export { default as BorderlinePersonalityDisorderIcon } from "./borderline-personality-disorder.svg";
// export { default as CyclothymiaIcon } from "./cyclothymia.svg";
// export { default as DysthymiaIcon } from "./dysthymia-persistent-epressive-disorder.svg";
// export { default as GeneralizedAnxietyDisorderIcon } from "./generalized-anxiety-disorder.svg";
// export { default as IntellectualDisabilityIcon } from "./intellectual-disability.svg";
// export { default as MajorDepressiveDisorderIcon } from "./major-depressive-disorder.svg";
// export { default as MoodDisordersImg1 } from "./mood-disorders-img-1.svg";
// export { default as MoodDisordersImg2 } from "./image-mood-two.svg";
// export { default as MoodDisordersImg3 } from "./mood-disorders-img-3.svg";
// export { default as MoodDisordersImg4 } from "./mood-disorders-img-4.svg";
// export { default as NarcolepsyIcon } from "./narcolepsy.svg";
// export { default as NeurodevelopmentalDisordersImg1 } from "./neurodevelopmental-disorders-img-1.svg";
// export { default as NeurodevelopmentalDisordersImg2 } from "./neurodevelopmental-disorders-img-2.svg";
// export { default as PanicDisorderIcon } from "./panic-disorder.svg";
// export { default as PersonalityDisordersImg1 } from "./personality-disorders-img-1.svg";
// export { default as PersonalityDisordersImg2 } from "./personality-disorders-img-2.svg";
// export { default as PsychoticDisordersImg1 } from "./psychotic-disorders-img-1.svg";
// export { default as PsychoticDisordersImg2 } from "./psychotic-disorders-img-2.svg";
// export { default as SleepWakeDisordersImg1 } from "./sleep-wake-disorders-img-1.svg";
// export { default as SleepWakeDisordersImg2 } from "./sleep-wake-disorders-img-2.svg";
// export { default as SocialAnxietyDisorderIcon } from "./social-anxiety-disorder.svg";
// export { default as SpecificPhobiasIcon } from "./specific-phobias.svg";
// export { default as ObsessiveCompulsiveDisorderImage } from "./obsessive-compulsive-disorder.svg";
// export { default as BodyDysmorphicDisordersImage } from "./body-dysmorphic-disorder.svg";
// export { default as ObsessiveCompulsiveDisorderPageImage } from "./obsessive-compulsive-disorder-img.svg";
// export { default as BodyDysmorphicDisorderPageImage } from "./body-dysmorphic-disorder-img.svg";
// export { default as AnorexiaNervosaIcon } from "./anorexia-nervosa-icon.svg";
// export { default as BulimiaNervosaIcon } from "./bulimia-nervosa-icon.svg";
// export { default as BingeEatingDisorderIcon } from "./binge-eating-disorder-icon.svg";
// export { default as AnorexiaNervosaPageImage } from "./anorexia-nervosa-page-img.svg";
// export { default as BulimiaNervosaPageImage } from "./bulimia-nervosa-img.svg";
// export { default as BingeEatingDisorderPageImage } from "./binge-eating-disorder-img.svg";
// export { default as PostTraumaticStressDisorderImage } from "./post-traumatic-stress-disorder-img.svg";
// export { default as backVector } from "./back-vector.svg";
// export { default as mainSection } from "./main.svg";
// export { default as section1 } from "./section1.svg";
// export { default as section2 } from "./section2.svg";
// export { default as section3 } from "./section3.svg";
// export { default as section4 } from "./section4.svg";
// export { default as section5 } from "./section5.svg";
// export { default as section6 } from "./section6.svg";
// export { default as section7 } from "./section7.svg";
// export { default as section8 } from "./section8.svg";
// export { default as section9 } from "./section9.svg";
// export { default as section10 } from "./section10.svg";
// export { default as homeImg } from "./home-img.svg";
// export { default as homeImg1 } from "./home-img1.svg";
// export { default as homeImg2 } from "./home-img2.svg";
// export { default as homeImg3 } from "./home-img3.svg";
// export { default as homeImg4 } from "./home-img4.svg";
// export { default as homeImg5 } from "./home-img5.svg";
// export { default as homeImg6 } from "./home-img6.svg";
// export { default as homeImg7 } from "./home-img7.svg";
// export { default as homeImg8 } from "./home-img8.svg";
// export { default as homeImg9 } from "./home-img9.svg";
// export { default as homeImg10 } from "./home-img10.svg";
// export { default as colorLegends } from "./color-legends.svg";
// export { default as AlzheimerDiseaseIcon } from "./alzheimer-disease-icon.svg";
// export { default as AlzheimerDiseaseImage } from "./alzheimer-disease-img.svg";
// export { default as ParkinsonDiseaseIcon } from "./parkinson-disease-icon.svg";
// export { default as ParkinsonDiseaseImage } from "./parkinson-disease-img.svg";
// export { default as AlcoholUseDisorderIcon } from "./alcohol-use-disorder-icon.svg";
// export { default as AlcoholUseDisorderImage } from "./alcohol-use-disorder-img.svg";
// export { default as DrugUseDisorderIcon } from "./drug-use-disorder-icon.svg";
// export { default as DrugUseDisorderImage } from "./drug-use-disorder-img.svg";
// export { default as ParaphilicDisordersImage } from "./paraphilic-disorders-img.svg";
// export {default as SomaticSymptomDisorderIcon} from "./somatic-symptom-disorder-icon.svg";
// export {default as SomaticSymptomDisorderImage} from "./somatic-symptom-disorder-img.svg";
// export {default as IllnessAnxietyDisorderIcon} from "./illness-anxiety-disorder-icon.svg";
// export {default as IllnessAnxietyDisorderImage} from "./illness-anxiety-disorder-img.svg";
// export {default as OppositionalDefiantDisorderIcon} from "./oppositional-defiant-disorder-icon.svg";
// export {default as OppositionalDefiantDisorderImage} from "./oppositional-defiant-disorder-img.svg";
// export {default as ConductDisorderIcon} from "./conduct-disorder-icon.svg";
// export {default as ConductDisorderImage} from "./conduct-disorder-img.svg";
// export { default as Insomnia } from "./insomnia.svg";
// export { default as SchizoaffectiveDisorders } from "./schizoaffective-disorders.svg";
// export { default as Schizophrenia } from "./Schizophrenia.svg";
// export { default as AttentionDeficitHyperactivityDisorder } from "./AttentionDeficitHyperactivityDisorder.svg";
// export { default as Dysthym } from "./Dysthym.svg"
// export { default as PsychiatricAssessmentMentalHealthDisordersImg1 } from "./PsychiatricAssessmentMentalHealthDisordersImg1.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg2 } from "./PsychiatricAssessmentMentalHealthDisordersImg2.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg3 } from "./PsychiatricAssessmentMentalHealthDisordersImg3.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg4 } from "./PsychiatricAssessmentMentalHealthDisordersImg4.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg5 } from "./PsychiatricAssessmentMentalHealthDisordersImg5.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg6 } from "./PsychiatricAssessmentMentalHealthDisordersImg6.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg7 } from "./PsychiatricAssessmentMentalHealthDisordersImg7.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg8 } from "./PsychiatricAssessmentMentalHealthDisordersImg8.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg9 } from "./PsychiatricAssessmentMentalHealthDisordersImg9.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg10 } from "./PsychiatricAssessmentMentalHealthDisordersImg10.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg11 } from "./PsychiatricAssessmentMentalHealthDisordersImg11.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg12 } from "./PsychiatricAssessmentMentalHealthDisordersImg12.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg13 } from "./PsychiatricAssessmentMentalHealthDisordersImg13.svg";
// export { default as PsychiatricAssessmentMentalHealthDisordersImg14 } from "./PsychiatricAssessmentMentalHealthDisordersImg14.svg";
export { default as logo2 } from "./logo2.jpg";
export { default as dashboardIcon1 } from "./dashboard-icon1.svg";
export { default as dashboardIcon2 } from "./dashboard-icon2.svg";
export { default as dashboardIcon3 } from "./dashboard-icon3.svg";
export { default as dashboardIcon4 } from "./dashboard-icon4.svg";
export { default as dashboardIcon5 } from "./dashboard-icon5.svg";
export { default as dashboardIcon6 } from "./dashboard-icon6.svg";
export { default as dashboardIcon7 } from "./dashboard-icon7.svg";
export { default as dashboardIcon8 } from "./dashboard-icon8.svg";
export { default as dashboardIcon9 } from "./dashboard-icon9.svg";
export { default as dashboardIcon10 } from "./dashboard-icon10.svg";
export { default as dashboardIcon11 } from "./dashboard-icon11.svg";
export { default as dashboardIcon12 } from "./dashboard-icon12.svg";
export { default as dashboardIcon13 } from "./dashboard-icon13.svg";
export { default as dashboardIcon14 } from "./dashboard-icon14.svg";
export { default as dashboardIcon15 } from "./dashboard-icon15.svg";
export { default as dashboardIcon16 } from "./dashboard-icon16.svg";
export { default as dashboardIcon17 } from "./dashboard-icon17.svg";
export { default as dashboardIcon18 } from "./dashboard-icon18.svg";
export { default as dashboardIcon19 } from "./dashboard-icon19.svg";
export { default as dashboardIcon20 } from "./dashboard-icon20.svg";
export { default as dashboardIcon21 } from "./dashboard-icon21.svg";
export { default as dashboardIcon22 } from "./dashboard-icon22.svg";
export { default as dashboardIcon23 } from "./dashboard-icon23.svg";
export { default as dashboardIcon24 } from "./dashboard-icon24.svg";
export { default as cobitPeriodicTable } from "./cobit-periodic-table.svg";
export { default as dashboardIcon26 } from "./dashboard-icon26.svg";
export { default as dashboardIcon27 } from "./dashboard-icon27.svg";
export { default as dashboardIcon28 } from "./dashboard-icon28.svg";
export { default as dashboardIcon29 } from "./dashboard-icon29.svg";
export { default as dashboardIcon30 } from "./dashboard-icon30.svg";
export { default as dashboardIcon31 } from "./dashboard-icon31.svg";
export { default as dashboardIcon32 } from "./dashboard-icon32.svg";
export { default as dashboardIcon33 } from "./dashboard-icon33.svg";
export { default as dashboardIcon34 } from "./dashboard-icon34.svg";
export { default as dashboardIcon35 } from "./dashboard-icon35.svg";
export { default as dashboardIcon36 } from "./dashboard-icon36.svg";
export { default as dashboardIcon37 } from "./dashboard-icon37.svg";
export { default as dashboardIcon38 } from "./dashboard-icon38.svg";
export { default as dashboardIcon39 } from "./dashboard-icon39.svg";
export { default as dashboardIcon40 } from "./dashboard-icon40.svg";
export { default as dashboardIcon41 } from "./dashboard-icon41.svg";
export { default as dashboardIcon42 } from "./dashboard-icon42.svg";
export { default as dashboardIcon43 } from "./dashboard-icon43.svg";
export { default as dashboardIcon44 } from "./dashboard-icon44.svg";
export { default as dashboardIcon45 } from "./dashboard-icon45.svg";
export { default as dashboardIcon46 } from "./dashboard-icon46.svg";
export { default as dashboardIcon47 } from "./dashboard-icon47.svg";
export { default as dashboardIcon48 } from "./dashboard-icon48.svg";
export { default as dashboardIcon49 } from "./dashboard-icon49.svg";
export { default as cobiTLogo } from "./cobit-logo.svg";
export { default as StrategyGovernanceMEA04ManagedAssuranceImage } from "./StrategyGovernanceMEA04ManagedAssuranceImage.svg";
export { default as StrategyGovernanceMEA01PerformanceMeasurementImage } from "./StrategyGovernanceMEA01PerformanceMeasurementImage.svg";
export { default as StrategyGovernanceEDM01ITGovernanceImage } from "./StrategyGovernanceEDM01ITGovernanceImage.svg";
export { default as StrategyGovernanceAPO08EDM05StakeholderRelationImage } from "./StrategyGovernanceAPO08EDM05StakeholderRelationImage.svg";
export { default as StrategyGovernanceAPO04InnovationImage } from "./StrategyGovernanceAPO04InnovationImage.svg";
export { default as StrategyGovernanceAPO02ITStrategyImage } from "./StrategyGovernanceAPO02ITStrategyImage.svg";
export { default as StrategyGovernanceAPO01ITManagementPoliciesImage } from "./StrategyGovernanceAPO01ITManagementPoliciesImage.svg";
export { default as PpmProjectsBai05OrganisationalChangeManagementImage } from "./PPMProjectsBAI05OrganisationalChangeManagementImage.svg";
export { default as PpmProjectsBai02RequirementsGatheringImage } from "./PPMProjectsBAI02RequirementsGatheringImage.svg";
export { default as PpmProjectsBai01ProjectManagementImage } from "./PPMProjectsBAI01ProjectManagementImage.svg";
export { default as PpmProjectsApo05PortfolioManagementImage } from "./PPMProjectsAPO05PortfolioManagementImage.svg";
export { default as SecurityRiskApo12Edm03RiskManagmentImage } from "./SecurityRiskAPO12EDMO3RiskManagmentImage.svg";
export { default as SecurityRiskApo13SecurityStrategyImage } from "./SecurityRiskAPO13SecurityStrategyImage.svg";
export { default as SecurityRiskDss04BusniessContinuityImage } from "./SecurityRiskDSS04BusniessContinuityImage.svg";
export { default as SecurityRiskDss04DisasterRecoveryPlanningImage } from "./SecurityRiskDSS04DisasterRecoveryPlanningImage.svg";
export { default as SecurityRiskSecurityManagementImage } from "./SecurityRiskSecurityManagementImage.svg";
export { default as SecurityRiskDssp6Mea02BusinessProcessControlsAndInternalAuditImage } from "./SecurityRiskDSSP6MEA02BusinessProcessControlsInternalAuditImage.svg";
export { default as SecurityRiskMea03ExternalComplianceImage } from "./SecurityRiskMEA03ExternalComplianceImage.svg";
export { default as FinancialManagementEdm04CostOptimisationImage } from "./FinancialManagementEDM04CostOptimisationImage.svg";
export { default as FinancialManagementEdm02BusinessValuesImage } from "./FinancialManagementEDM02BusinessValuesImage.svg";
export { default as FinancialManagementApo10VendorManagementImage } from "./FinancialManagementAPO10VendorManagementImage.svg";
export { default as FinancialManagementApo06CostBudgetManagementImage } from "./FinancialManagementAPO06CostBudgetManagementImage.svg";
export { default as DataBiItrg08DataQualityImage } from "./DataBIITRG08DataQualityImage.svg";
export { default as DataBiItrg07DataArchitectureImage } from "./DataBIITRG07DataArchitectureImage.svg";
export { default as DataBiItrg06BusinessIntelligenceReportingImage } from "./DataBIITRG06BusinessIntelligenceReportingImage.svg";
export { default as DataBiApo14ManagedDataImage } from "./DataBIAPO14ManagedDataImage.svg";
export { default as InfrastructureOperationsDss01OperationsManagementImage } from "./InfrastructureOperationsDSS01OperationsManagementImage.svg";
export { default as StrategyGovernanceBai06ChangeManagementImage } from "./StrategyGovernanceBAI06ChangeManagementImage.svg";
export { default as InfrastructureOperationsBai09AssetManagementImage } from "./InfrastructureOperationsBAI09AssetManagementImage.svg";
export { default as InfrastructureOperationsBai10ConfigurationManagementImage } from "./InfrastructureOperationsBAI10ConfigurationManagementImage.svg";
export { default as InfrastructureOperationsBai0ReleaseManagementImage } from "./InfrastructureOperationsBAI0ReleaseManagementImage.svg";
export { default as InfrastructureOperationsDss02ServiceDeskImage } from "./InfrastructureOperationsDSS02ServiceDeskImage.svg";
export { default as InfrastructureOperationsDss03IncidentAndProblemManagmentImage } from "./InfrastructureOperationsDSS03IncidentProblemManagmentImage.svg";
export { default as InfrastructureOperationsBai04AvailabilityAndCapacityManagementImage } from "./InfrastructureOperationsBAI04AvailabilityCapacityManagementImage.svg";
export { default as ApplicationsAppsItrag05ApplicationMaintainanceImage } from "./ApplicationsITRG05ApplicationMaintainanceImage.svg";
export { default as ApplicationsAppsItrag04ApplicationPortfolioManagementImage } from "./ApplicationsITRG04ApplicationPortfolioManagementImage.svg";
export { default as ApplicationsAppsBai07ApplicationDevelopmentQualityImage } from "./ApplicationsBAI07ApplicationDevelopmentQualityImage.svg";
export { default as ApplicationsAppsBai03EnterpriseApplicationSelectionImplementationImage } from "./ApplicationsBAI03EnterpriseApplicationSelectionImplementationImage.svg";
export { default as PeopleResourcesITOrganisationalDesignImage } from "./PeopleResourcesITOrganisationalDesignImage.svg";
export { default as PeopleResourcesLeadershipCulturalValuesImage } from "./PeopleResourcesLeadershipCulturalValuesImage.svg";
export { default as PeopleResourcesKnowledgeManagementImage } from "./PeopleResourcesKnowledgeManagementImage.svg";
export { default as PeopleResourcesHumanResourcesManagementImage } from "./PeopleResourcesHumanResourcesManagementImage.svg";
export { default as ServicePlanningArchitectureITRG03ManageServiceCatalogsImage } from "./ServicePlanningArchitectureITRG03ManageServiceCatalogsImage.svg";
export { default as ServicePlanningArchitectureBAI11ManagedProjectsImage } from "./ServicePlanningArchitectureBAI11ManagedProjectsImage.svg";
export { default as ServicePlanningArchitectureAPO11QualityManagementAuditFormImage } from "./ServicePlanningArchitectureAPO11QualityManagementAuditFormImage.svg";
export { default as ServicePlanningArchitectureAPO09ServiceManagementAuditFormImage } from "./ServicePlanningArchitectureAPO09ServiceManagementAuditFormImage.svg";
export { default as ServicePlanningArchitectureAPO03EnterpriseArchitectureImage } from "./ServicePlanningArchitectureAPO03EnterpriseArchitectureImage.svg";
